# Permalinks
permalink:           pretty

# Setup
title:               'Nicholas Wold'
url:                 https://nicholaswold.com
tagline:             The personal blog of Nicholas Wold
paginate:            1000
paginate_path:       "/page:num/"
baseurl:             ""

# Includes
include:
  - _redirects

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Nicholas Wold
  url:               https://github.com/nicholaswold
  email:             nick@nicholaswold.com

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/nicholaswold/nicholaswold.github.io

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-gist
